// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buaoztfaudwpohoftfwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1YW96dGZhdWR3cG9ob2Z0ZndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0OTg4MzQsImV4cCI6MjA1NjA3NDgzNH0.TM6C9yKRu_EGHRgDxdygdMTUmdD_8zTRi4ulXyEse24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);